### ISSUE TITLE
unknown-file(1,1): Error FS0078: Unable to find the file 'FSharp.Data.SqlProvider' in any of  /Library/Frameworks/Mono.

### ISSUE THREAD

**Issue by ajonno** [rachelblasucci/Tasky#1]
getting this (single) error when trying to build on Xamarin Studio. 

unknown-file(1,1): Error FS0078: Unable to find the file 'FSharp.Data.SqlProvider' in any of  /Library/Frameworks/Mono.....

Also could not seem to find FSharp.Data.SqlProvider on NuGet?

**Comment by rachelblasucci** [comment]
Use the dll in the References folder.
