### ISSUE TITLE
Could not load type 'Microsoft.FSharp.Linq.QueryBuilder' from assembly

### ISSUE THREAD

**Issue by ajonno** [rachelblasucci/Tasky#2]
hi, couple items:
- the db path in Data.fs shows your personal Dropbox path. might be worth putting generic placeholder text here and letting users know to add in their own path ?
- once the path is resolved, then getting this new build error:

Could not load type 'Microsoft.FSharp.Linq.QueryBuilder' from assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by rachelblasucci** [comment]
Ah, good call on removing my path. I'd be meaning to do that. Thanks! 

For the second, yes, this one was super tricky to resolve for me. 
If neither updating MonoTouch to the latest version, nor using the FSharp.Core that comes in the latest  version of Mono work, you might have to compile F#. Or, you can use a slightly different syntax in place of query: 

```
    ctx.``[main].[tasks]``
        |> Seq.filter (fun t -> t.complete = 0L)
        |> Seq.map (fun t -> {Description=t.task; Complete=false})
        |> Seq.toList
```

Let me know how it goes!

**Comment by ajonno** [comment]
hi Rachel, uhf I still can’t seem to get it running w/ this particular type provider.   

I’m running:  
Macbook Pro 2.3 GHz Intel Core i7 ; 16Gb ram
Xam Studio 5.1 Build 479
mtouch 7.2.5.5 (87026b6)

(just for reference, the “Shallow” sample F# project works fine for me)

also tried switching from mono runtime 3.4 to 3.6.

I also inserted the code snippet below like so, in Data.fs but still got the same compile error.

  let GetIncompleteTasks () = 
        ctx.`[main].[tasks]`
            |> Seq.filter (fun t -> t.complete = 0L)
            |> Seq.map (fun t -> {Description=t.task; Complete=false})
            |> Seq.toList 

From build log:
Building: Tasky (Debug | iPhoneSimulator)
Performing main compilation...
/Library/Frameworks/Mono.framework/Versions/3.4.0/bin/fsharpc --noframework --nologo
-r:"/Library/Frameworks/Mono.framework/Versions/3.4.0/lib/mono/2.0/mscorlib.dll"
-r:"/Developer/MonoTouch/usr/lib/mono/2.1/FSharp.Core.dll"
-r:"/Developer/MonoTouch/usr/lib/mono/2.1/Mono.Data.Sqlite.dll"
-r:"/Developer/MonoTouch/usr/lib/mono/2.1/System.Core.dll"
-r:"/Developer/MonoTouch/usr/lib/mono/2.1/System.Data.dll"
-r:"/Developer/MonoTouch/usr/lib/mono/2.1/System.Xml.dll"
-r:"/Developer/MonoTouch/usr/lib/mono/2.1/System.dll"
Build complete -- 1 error, 0 warnings

---------------------- Done ----------------------

Build: 1 error, 0 warnings

Is this sort of (type provider) problem typical w/ F# projects ? I’m absolute loving the language and have spent some solid time educating myself on it so far, however issues like this make me a bit ‘nervous’. For example is the tooling and API set for Xamarin projects not stable & ready for prod use ?

cheers
Angus

**Comment by 7sharp9** [comment]
@rachelreese @ajonno I think this is caused from using an older version of `FSharp.Core` that was packaged in monotouch.  

@rachelreese It may be worth comparing your version of monotouch with @ajonno 's

I have this working on my machine and Im using:

```
Xamarin.iOS
Version: 7.2.6.7 (Business Edition)
Hash: c19d551
Branch: 
Build date: 2014-06-26 18:49:51-0400
```

`Shallow` is working because it doesn't use Type Providers.  Type providers require the type `FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute`and `Microsoft.FSharp.Linq.QueryBuilder` which are not present in the older version of `FSharp.core` that was included with monotouch.  

It may be worth moving to the Xamarin beta or alpha channels to get the newer version of monotouch, which I think will rectify this.

**Comment by ajonno** [comment]
i upgraded Xamarin Studio to _alpha_ release and the Tasky app now compiles and runs ok. thanks for your help w/ this. 

# 

just to note - i also tried to run Tasky after changing preferences in Xam Studio to point to iOS 8 —> /Applications/Xcode6-Beta3.app .  Tasky crashed with this log error :

2014-07-10 23:36:32.925 Tasky[14699:874415] **\* Assertion failure in -[UIApplication applicationWillOrderInContext:forWindow:], /SourceCache/UIKit_Sim/UIKit-3262.1/UIApplication.m:10117

**Comment by 7sharp9** [comment]
Does the C# version also do that?

**Comment by ajonno** [comment]
i just downloaded/tested the C# version ; it builds ok, but the iOS simulator didn't launch. seeing this error:

warning MT1201: Could not load the simulator: dlopen(/Applications/Xcode6-Beta3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/DVTiPhoneSimulatorRemoteClient.framework/Versions/A/DVTiPhoneSimulatorRemoteClient, 1): image not found
